### ISSUE TITLE
NEON citation

### ISSUE THREAD

**Issue by jsanderman** [soilspectroscopy/ossl-imports#1]
There is a standard citation that NEON wants with there data -

Soil samples were provided from the National Ecological Observatory Network (NEON) Megapit Soil Archive. NEON is a program sponsored by the National Science Foundation and operated under cooperative agreement by Battelle. This material is based in part upon work supported by the National Science Foundation through the NEON Program.

Can you please add when you get a chance?

Thanks

**Comment by thengl** [comment]
Please check if this is acceptable: https://soilspectroscopy.github.io/ossl-manual/index.html#acknowledgments
