### ISSUE TITLE
organic carbon for AfSIS1

### ISSUE THREAD

**Issue by jsanderman** [soilspectroscopy/ossl-imports#3]
AfSIS1 database has SOC measured as total carbon after acidification and this is reported in a column called "acidified carbon" which is the last column in this dataset (https://github.com/zecojls/SoilSpec4GG_GoogleColab/blob/main/data/AFSIS_ICRAFwetchem.csv).

ICRAF's method for organic carbon is described here: https://worldagroforestry.org/sites/default/files/Total%20organic%20carbon%20and%20nitrogen_221111.pdf

**Comment by jsanderman** [comment]
I also think the same issue is in the Central Africa SSL - they measured TC but almost all of the samples are highly acidic so TC = TOC. For CASSL, we can be conservative and say TC = TOC only where pH was measured and pH < 7.0.

**Comment by thengl** [comment]
The TOC has been re-imported as you suggested for AfSIS and CASSL. See e.g.: https://github.com/soilspectroscopy/ossl-imports/tree/main/dataset/CASSL#soil-lab-information
